# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 13:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('seats', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), max_length=10, size=None)),
                ('seance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.Seance')),
            ],
        ),
    ]
