# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Seance'),
        ),
    ]
