# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('original_title', models.CharField(max_length=20)),
                ('poster_url', models.CharField(max_length=50)),
                ('trailer_url', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='moviegenre',
            name='mg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaapp.Movies'),
        ),
        migrations.AddField(
            model_name='genres',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaapp.MovieGenre'),
        ),
    ]
