# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='description',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='moviegenre',
            name='genre',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='moviegenre',
            name='movie',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='cast',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='format',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='summary',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='original_title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster_url',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='trailer_url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
